name: Test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  with-input:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]
        include:
          - os: ubuntu-latest
            version: "2.5.0" # should be 2.5.0
          - os: macos-latest
            version: "2.1" # should be 2.1.1
          - os: windows-latest
            version: "2" # should be 2.5.0
          - os: macos-13
            version: "1.x" # should be 1.1.4
            

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup catppuccin/whiskers
        uses: ./
        with:
          whiskers-version: ${{ matrix.version }}
      - run: whiskers --version

  without-input:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup catppuccin/whiskers
        uses: ./
      - run: whiskers --version # should be 2.1.0
