name: Test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  with-input:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            version: "^2" # should be latest 2.x
          - os: windows-latest
            version: "2.5.0" # should be 2.5.0
          - os: macos-latest
            version: "2.3" # should be 2.3.0
            

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup catppuccin/whiskers
        uses: ./
        with:
          whiskers-version: ${{ matrix.version }}
      - run: whiskers --version

  without-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup catppuccin/whiskers
        uses: ./
      - run: whiskers --version # should be latest 2.x
